# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: dsvmbuildagent-gpu
  vmImage: 'cvbp-linuxbuildagent'

steps:

- bash:
    'which conda &&
    echo ONE &&
    env | sort > env11.txt &&
    cat env11.txt &&
    source /data/anaconda/etc/profile.d/conda.sh &&
    yes | conda env remove -n cvbp && 
    conda env create --quiet -f image_classification/environment.yaml &&
    conda env list &&
    echo TWO &&
    env | sort > env22.txt &&
    cat env22.txt &&
    source activate cvbp &&
    which conda' 
  displayName: 'Create cvbp conda environment'

- bash:
    'which conda &&
     source ~/.bashrc &&
     source activate cvbp &&
     pytest image_classification/tests/unit'
  displayName: 'Activate cvbp conda environment'

