# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: dsvmbuildagent-gpu
  vmImage: 'cvbp-linuxbuildagent'

steps:

- bash:
    'which conda &&
    source ~/.bashrc &&
    yes | conda env remove -n cvbp && 
    conda env create --quiet -f image_classification/environment.yaml &&
    conda env list &&
    source activate cvbp
    which conda' 
  displayName: 'Create cvbp conda environment'

- bash:
    'which conda &&
     source ~/.bashrc &&
     source activate cvbp'
  displayName: 'Activate cvbp conda environment'

- bash: 
    'echo "Unit Tests" && \
    pytest image_classification/tests/unit && \
    source deactivate'
  displayName: 'Run Unit Test'