# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: dsvmbuildagent-gpu
  vmImage: 'cvbp-linuxbuildagent'

steps:

- script: |
    . /data/anaconda/etc/profile.d/conda.sh
    conda env remove -n cvbp
    conda env create --quiet -f image_classification/environment.yaml 2> log
  displayName: 'Create cvbp conda environment'

- script: |
    . /data/anaconda/etc/profile.d/conda.sh
    conda activate cvbp
  displayName: 'Activate cvbp conda environment'

- script: |
    . /data/anaconda/etc/profile.d/conda.sh
    echo "Unit Tests"
    pytest image_classification/tests/unit
    conda deactivate
  displayName: 'Run Unit Test'