
trigger:
- staging

pool:
  name: cvbpbuildagents
  vmImage: 'linuxagent-gpu'

steps:

- bash: |
    echo "##vso[task.prependpath]/data/anaconda/bin"
  displayName: Add Conda to PATH

- bash: |
    conda create -q -n cvbp python=3.5 -y
    conda env update -q -n cvbp -f image_classification/environment.yaml
  displayName: 'Conda install dependencies'

- bash: |
    source activate cvbp
    pytest image_classification/tests/unit --junitxml=junit/test-unitttest.xml
  displayName: 'tests'
