# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: dsvmbuildagent-gpu
  vmImage: 'cvbp-linuxbuildagent'

steps:

- script: |
    yes | /data/anaconda/envs/py35/bin/conda env remove -n cvbp
    /data/anaconda/envs/py35/bin/conda env create --quiet -f image_classification/environment.yaml 2> log
  displayName: 'Create cvbp conda environment'

- script: |
    /data/anaconda/envs/py35/bin/conda activate cvbp
  displayName: 'Activate cvbp conda environment'

- script: |
    echo "Unit Tests"
    pytest image_classification/tests/unit
    /data/anaconda/envs/py35/bin/conda deactivate
  displayName: 'Run Unit Test'