# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: dsvmbuildagent-gpu
  vmImage: 'cvbp-linuxbuildagent'

steps:

- bash:
    'which conda &&
    conda env create --quiet -f image_classification/environment.yaml &&
    conda env list &&
    conda activate cvbp' 
  displayName: 'Create cvbp conda environment'

- bash:
    'which conda && \
    conda activate cvbp'
  displayName: 'Activate cvbp conda environment'

- bash: 
    'echo "Unit Tests" && \
    pytest image_classification/tests/unit && \
    conda deactivate'
  displayName: 'Run Unit Test'