# To create the conda environment:
# $ conda env create -f environment.yml
# 
# To update the conda environment:
# $ conda env update -f environment.yml
# 
# To register the conda environment in Jupyter:
# $ conda activate cv
# $ python -m ipykernel install --user --name cv
# 
name: cv-org
channels:
- pytorch
- fastai
- defaults
- conda-forge
dependencies:
- python==3.7.6
- pytorch==1.2.0
# pinning pillow to 6.1 to fix issue: https://github.com/python-pillow/Pillow/issues/4130
- pillow==6.1 
- torchvision==0.4.0
- fastai==1.0.57
- ipykernel>=4.6.1
- jupyter>=1.0.0
